blueprint:
  name: Bloomin8 - Random Picture
  description: Automatically changes the picture of a Bloomin8 picture frame when it comes online to a random picture from a given media source
  domain: automation
  author: BottlecapDave
  input:
    target_frame_entity:
      name: Target Frame
      description: The frame to change the picture on
      selector:
        entity:
          filter:
          - domain:
            - media_player
          reorder: false
          multiple: false
    target_frame_device_tracker_entity:
      name: Target Frame device tracker
      description: The device tracker that determines the picture frame has come online
      selector:
        entity:
          filter:
          - domain:
            - device_tracker
          reorder: false
          multiple: false
    album_media_source:
      name: Album media source entity
      description: The entity that indicates the album media source to randomly get a picture from. this should return an album media source (e.g. media-source://immich/ce4812db-ee05-41a4-9a66-8dc20efe6d98|albums|6bd88cd0-67ad-46f0-a1cb-af3b4895e5e0). This is an entity so that you can dynamically change the source if needed (e.g. a template sensor).
      selector:
        entity:
          filter:
          - domain:
            - sensor
    additional_conditions:
      name: Additional conditions
      description: Extra conditions you may want to add to this automation
      default: []
      selector:
        condition: {}
    min_hours_between_triggers:
      name: Minimum hours between triggers
      description: The minimum number of hours between picture changes so that if the device comes online multiple times it does not change every time
      default: 20
      selector:
        number:
          min: 0.0
          max: 72.0
          step: 1.0
          mode: slider
trigger_variables:
  target_frame_entity: !input target_frame_entity
  target_frame_device_tracker_entity: !input target_frame_device_tracker_entity
  album_media_source: !input album_media_source
  min_hours_between_triggers: !input min_hours_between_triggers
mode: queued
triggers:
- trigger: state
  entity_id: !input target_frame_device_tracker_entity
  to: home
conditions:
- condition: template
  value_template: >
    {{ (now() - this.attributes.last_triggered) > timedelta(hours=min_hours_between_triggers) }}
- and: !input additional_conditions
actions:
- action: media_player.browse_media
  data:
    media_content_type: image
    media_content_id: '{{ states(album_media_source) }}'
  target:
    entity_id: !input target_frame_entity
  response_variable: response
- variables:
    image: >
      {% set ns = namespace(items=[]) %}
      {% for item in response[target_frame_entity].children %}
        {% set ns.items = ns.items + [{
          'id': item.media_content_id,
          'type': item.media_content_type
        }] %}
      {% endfor %}
      {{ ns.items | random }}
    content_id: '{{ image.id }}'
    content_type: '{{ image.type }}'
- action: media_player.play_media
  target:
    entity_id: !input target_frame_entity
  data:
    media:
      media_content_id: '{{ content_id }}'
      media_content_type: '{{ content_type }}'
